# Generated by Django 5.1 on 2024-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icard', '0003_person_current_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
